"""empty message

Revision ID: 079bce331988
Revises: bf9a605bcb54
Create Date: 2023-05-15 18:22:51.087691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079bce331988'
down_revision = 'bf9a605bcb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_detail')
    # ### end Alembic commands ###
